pools:
  - name: hostpalace-public-ipv4
    cidr: 192.142.24.0/21
    gateway: 192.142.24.1
    dns:
      - 8.8.8.8
      - 1.1.1.1
    reserved:
      - 192.142.24.0     # network address
      - 192.142.24.1     # gateway
      - 192.142.31.255   # broadcast
